export const PENDING = 'PENDING';
export const FULFILLED = 'FULFILLED';
export const FAILED = 'FAILED';
export const DEFAULT = 'DEFAULT';
export const SUCCESS = 'SUCCESS';
export const COMPLETE = 'Complete';
export const INPROGRESS = 'In-Progress';
export const DISMISS = 'DISMISS';
export const SERVER_DOWN_MSG = "Seems like server is down, please check After some time";
export const FAILURE = 'FAILURE'